services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: today_meal
      POSTGRES_PASSWORD: today_meal_dev
      POSTGRES_DB: today_meal
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
